#ifndef CONFIG_H
#define CONFIG_H

#define CONFIG_WINDOW_WIDTH 800
#define CONFIG_WINDOW_HEIGHT 600
#define CONFIG_WINDOW_NAME "window"
#define CONFIG_APP_VERSION_MAJOR 0
#define CONFIG_APP_VERSION_MINOR 1
#define CONFIG_APP_VERSION_PATCH 0
#define CONFIG_APP_NAME "app"
#define CONFIG_ENGINE_VERSION_MAJOR 0
#define CONFIG_ENGINE_VERSION_MINOR 1
#define CONFIG_ENGINE_VERSION_PATCH 0
#define CONFIG_ENGINE_NAME "krisvers' engine"

#endif
